# Tile first ghostty window.
# Doesn't work right since new windows aren't detected if app already open
# initial-command = aerospace tile first window

# appearance
theme = Kanagawa Dragon
font-size = 14
# font-family = MesloLGL Nerd Font Mono
# selection-foreground = ff0000
# selection-background = ff0000
cursor-color = orange red
cursor-text = white
macos-titlebar-style = tabs
macos-window-shadow = false
macos-icon = chalkboard

# tab/window
window-new-tab-position = current

# quick-term
quick-terminal-position = center
quick-terminal-screen = mouse
quick-terminal-animation-duration = 0.1
quick-terminal-autohide = true

# misc
clipboard-read = allow
clipboard-write = allow
clipboard-trim-trailing-spaces = true
clipboard-paste-protection = true
clipboard-paste-bracketed-safe = true
copy-on-select = false
macos-option-as-alt = true

# scrollback 10MB
scrollback-limit = 10000000
